[project]
name = "my-python-script-template"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "markdownify>=1.1.0",
    "pymupdf>=1.26.3",
    "requests>=2.32.3",
    "ruff>=0.12.2",
]
