"""Type stubs for PyMuPDF (fitz module)."""

from typing import List, Tuple
from pathlib import Path

class Pixmap:
    n: int
    alpha: int

    def __init__(self, doc: Document, xref: int) -> None: ...
    def save(self, filename: str | Path) -> None: ...

class Page:
    def get_text(self) -> str: ...
    def get_images(self, full: bool = False) -> List[Tuple[int, ...]]: ...

class Document:
    def __len__(self) -> int: ...
    def load_page(self, page_num: int) -> Page: ...
    def close(self) -> None: ...

def open(filename: str | Path) -> Document: ...
